jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        # usuario administrador que puede hacer cualquier cosa
        - id: ${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}
          name: ${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}
          password: ${JENKINS_PASSWORD_ADMINISTRADOR:-AdministradorTFG2024}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}"
        - 'Overall/Read:authenticated'

unclassified:
  location:
    url: http://servidor-jenkins:8080

jobs:
  # pipeline que se ejecuta correctamente
  - script: >
      freeStyleJob('7-pipeline-proyecto-powershell-correcto') {
        scm {
          git {
            remote {
              github('tfg2asircanaveral2024/7-proyecto-powershell')
            }
            branches('*/correcto')
          }
        }
        steps {
          shell('''
            pwsh ./script-jenkins.ps1
            chmod u+x script-despliegue-git.sh
            ./script-despliegue-git.sh
          ''')
        }
      }
  # pipeline que se ejecuta con errores
  - script: >
      freeStyleJob('7-pipeline-proyecto-powershell-incorrecto') {
        scm {
          git {
            remote {
              github('tfg2asircanaveral2024/7-proyecto-powershell')
            }
            branches('*/incorrecto')
          }
        }
        steps {
          shell('''
            pwsh ./script-jenkins.ps1
            chmod u+x script-despliegue-git.sh
            ./script-despliegue-git.sh
          ''')
        }
      }